local plugin = require("plugin_name")

describe("plugin entrypoint should", function()
  it("expose setup({}) function", function()
    assert.has.errors(function()
      plugin.setup("string")
    end)
    assert.has.errors(function()
      plugin.setup(123)
    end)
    assert.has_no.errors(function()
      plugin.setup({})
    end)
  end)

  it("not expose config table", function()
    assert.equals(nil, plugin.config)
  end)

  it("read setup", function()
    plugin.setup({})
    assert.equals(5, plugin.do_the_thing(2, 3))
    plugin.setup({ what_to_do = "multiply" })
    assert.equals(6, plugin.do_the_thing(2, 3))
  end)
end)
