---
on: [push, pull_request]
name: Test

jobs:
  stylua:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download tarball
        run: curl -OL https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz

      - name: Extract tarball
        run: tar xzvf nvim-linux64.tar.gz

      - name: run tests
        run: make test-ci
