---
on: [push, pull_request]
name: default

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          curl -OL https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
          sudo apt install ./nvim-linux64.deb

      - name: run tests
        run: make test
